name: task_mangement
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  http: ^1.2.2
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^9.2.4
  logger: ^1.0.0
  # bloc_test: ^10.0.0
  # mockito: ^5.4.0
  # build_runner: ^2.4.13
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  # mockito: ^5.4.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
